image: node:latest

stages:
  - frontend-build

frontend-build:
  type: deploy
  stage: frontend-build
  image: ruby:latest
  tags: 
    - dalfcs_gitlab_docker_ci
  only:
    - dev_aditya
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_ASSIGNMENT1 --api-key=$HEROKU_API_KEY
